on:
  release:
    types: [created]

jobs:
  release:
    # env:
    #   GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows
            target: i686-pc-windows-msvc
            runner: windows-latest

          - name: Linux
            target: x86_64-unknown-linux-gnu
            runner: ubuntu-latest

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v3

      - name: Update Rust Toolchain
        run: rustup update stable

      - name: Add Rust Target
        run: rustup target add ${{ matrix.target }}

      - name: Build Release Binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload Binary Artifact (Windows)
        uses: actions/upload-artifact@v4 # Use the upload-artifact action
        if: ${{ matrix.runner == 'windows-latest' }}
        with:
          name: vrc-log-${{ matrix.target }} # Name for the artifact bundle
          path: ./target/${{ matrix.target }}/release/vrc-log.exe # Path to the file to upload

      - name: Upload Binary Artifact (Linux)
        uses: actions/upload-artifact@v4 # Use the upload-artifact action
        if: ${{ matrix.runner == 'ubuntu-latest' }}
        with:
          name: vrc-log-${{ matrix.target }} # Name for the artifact bundle
          path: ./target/${{ matrix.target }}/release/vrc-log # Path to the file to upload
